// lightningcss 1.32.0 incorrectly rejects some ::file-selector-button selectors
// generated by @tailwindcss/forms. This plugin normalizes them before minification.
const USER_ACTION_PSEUDOS = new Set([':hover', ':active', ':focus', ':focus-within', ':focus-visible']);

const fixFileSelectorButton = () => ({
  postcssPlugin: 'fix-file-selector-button',
  Rule(rule) {
    if (!rule.selector.includes('::file-selector-button')) return;

    // Remove rules with a combinator after ::file-selector-button — truly invalid CSS.
    if (/::file-selector-button\s*[>~+]/.test(rule.selector)) {
      rule.remove();
      return;
    }

    // Move any non-user-action pseudo-classes from after ::file-selector-button to before it.
    // e.g. ::file-selector-button:disabled       → :disabled::file-selector-button
    //      ::file-selector-button:disabled:hover → :disabled:hover::file-selector-button
    rule.selector = rule.selector.replace(
      /(::file-selector-button)((?::[a-z-]+)+)/g,
      (_, pseudoEl, pseudoClasses) => {
        const classes = pseudoClasses.match(/:[a-z-]+/g) || [];
        const before = classes.filter((c) => !USER_ACTION_PSEUDOS.has(c));
        const after = classes.filter((c) => USER_ACTION_PSEUDOS.has(c));
        return before.join('') + pseudoEl + after.join('');
      },
    );
  },
});
fixFileSelectorButton.postcss = true;

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    fixFileSelectorButton,
  ],
};
