name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: 9.0.5
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store
      - name: Install dependencies
        run: pnpm i --frozen-lockfile && cd apps/website && pnpx playwright install --with-deps && pnpm exec playwright install
      - name: Run tests
        id: e2e
        run: cd apps/website && pnpm test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_PW: ${{ secrets.TEST_PW }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
      - name: Upload test artifacts
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: apps/website/test-results
