name: 'Pr Checks'
on:
  pull_request:

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: 9.0.5
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm prettier:check
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: 9.0.5
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
